---
- name: create build directories
  file:
    state=directory
    path={{ item }}
  with_items:
    - "{{ gobuild_dir }}"
    - "{{ gobuild_gitconfig | dirname }}"
    - "{{ gobuild_dir }}/bin"
    - "{{ gobuild_dir }}/src"
    - "{{ gobuild_dir }}/src/{{ gobuild_project_path }}"

- name: checkout code to build dir - no key
  git:
    repo={{ gobuild_repo_url }}
    version={{ gobuild_repo_version }}
    depth=1
    update=yes
    accept_hostkey=yes
    dest={{ gobuild_dir }}/src/{{ gobuild_project_path }}
    force=yes
    recursive=yes
  when: "{{ gobuild_keyfile|length == 0 }}"

- name: checkout code to build dir - with key
  git:
    repo={{ gobuild_repo_url }}
    version={{ gobuild_repo_version }}
    depth=1
    update=yes
    accept_hostkey=yes
    dest={{ gobuild_dir }}/src/{{ gobuild_project_path }}
    force=yes
    recursive=yes
    key_file={{ gobuild_keyfile }}
  when: "{{ gobuild_keyfile|length > 0 }}"

- name: build with commands
  shell: "eval `ssh-agent -s`;ssh-add {{ gobuild_keyfile }}; {{ item }}; eval `ssh-agent -k`"
  args:  
    chdir: "{{ gobuild_dir }}/src/{{ gobuild_project_path }}/"
  environment:
    GOPATH: "{{ gobuild_dir }}"
    GOBIN: "{{ gobuild_dir }}/bin"
    GOROOT: "{{ gobuild_goroot }}"
    PATH: "{{ ansible_env.PATH }}:{{ gobuild_goroot }}/bin:{{ gobuild_dir }}/bin"
  with_items: gobuild_commands
  when: gobuild_commands|length > 0

- name: build with go build
  include: gobuild.yml
  when: gobuild_commands|length == 0


