---

- name: depend - debian - install dependencies
  apt:
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
    - git
    - make
    - curl
    - mercurial
  when: ansible_os_family == 'Debian'

- name: depend - is go installed
  stat: path=~/.gimme/envs/latest.env
  register: golang

- name: depend - install go with gimme
  shell: 'eval "$(curl -sL https://raw.githubusercontent.com/meatballhat/gimme/master/gimme | GIMME_GO_VERSION={{ gobuild_go_version }} bash)"'
  when: not golang.stat.exists and gobuild_strict

- name: depend - get gimme global
  get_url:
    url: "https://raw.githubusercontent.com/meatballhat/gimme/master/gimme"
    dest: /usr/local/bin
    mode: 0755
  when: not gobuild_strict

- name: depend - install go with gimme
  shell: "gimme {{ gobuild_go_version }}"
  when: not gobuild_strict

- name: get gopath from gimme
  shell: cat ~/.gimme/envs/latest.env | grep GOROOT | awk 'BEGIN { FS="=";} { print $2;}' | awk ' BEGIN { FS="\"";} { print $2;}'
  register: gimme_gopath
  changed_when: False
 
- set_fact:
    gobuild_goroot: "{{gimme_gopath.stdout}}"

- name: create keyfile destination
  file:
    state=directory
    path={{ gobuild_keyfile|dirname }}
  when: gobuild_keyfile_local

- name: copy local keyfile
  copy:
    src={{ gobuild_keyfile_local }}
    dest={{ gobuild_keyfile }}
    mode=0600
  when: gobuild_keyfile_local
