---

#S3
#
#local

- name: deploy - get git revision
  shell: git rev-parse --short HEAD 2>/dev/null
  args:
    chdir: "{{ gobuild_dir }}/src/{{ gobuild_project_path }}"
  register: git_rev
  changed_when: false

- name: deploy - get project name
  shell: printf '%s\n' "${PWD##*/}"
  args:
    chdir: "{{ gobuild_dir }}/src/{{ gobuild_project_path }}"
  register: project_name
  changed_when: false

- name: deploy - create local deploy target
  file: 
    path={{ gobuild_deploy_dest}}/{{ project_name.stdout }}
    state=directory

- name: deploy - deploy local
  shell: "cp {{ gobuild_dir }}/bin/* {{ gobuild_deploy_dest}}/{{ project_name.stdout }}"

- name: deploy - get git revision
  shell: git rev-parse --short HEAD 2>/dev/null
  args:
    chdir: "{{ gobuild_dir }}/src/{{ gobuild_project_path }}"
  register: git_rev
  changed_when: false

- name: deploy - create git rev file
  copy: content="{{ git_rev.stdout }}" dest="{{ gobuild_deploy_dest}}/{{ project_name.stdout }}/_githash"

- name: deploy - get version number
  shell: cat VERSION
  args:
    chdir: "{{ gobuild_dir }}/src/{{ gobuild_project_path }}"
  register: version
  changed_when: false
  failed_when: false

- name: deploy - create version file
  copy: content="{{ version.stdout }}" dest="{{ gobuild_deploy_dest}}/{{ project_name.stdout }}/_version"
  when: version.rc == 0


